// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DemoCorsoBlazor.API.Models;

public partial class Certifications
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public int SpeakerId { get; set; }

    public virtual ICollection<Speakers> Speakers { get; set; } = new List<Speakers>();
}