// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DemoCorsoBlazor.API.Models;

public partial class EventiContext : DbContext
{
    public EventiContext(DbContextOptions<EventiContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Certifications> Certifications { get; set; }

    public virtual DbSet<Eventi> Eventi { get; set; }

    public virtual DbSet<Speakers> Speakers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Certifications>(entity =>
        {
            entity.Property(e => e.Nome).IsRequired();

            entity.HasMany(d => d.Speakers).WithMany(p => p.Certifications)
                .UsingEntity<Dictionary<string, object>>(
                    "CertificationSpeaker",
                    r => r.HasOne<Speakers>().WithMany().HasForeignKey("SpeakersId"),
                    l => l.HasOne<Certifications>().WithMany().HasForeignKey("CertificationsId"),
                    j =>
                    {
                        j.HasKey("CertificationsId", "SpeakersId");
                        j.HasIndex(new[] { "SpeakersId" }, "IX_CertificationSpeaker_SpeakersId");
                    });
        });

        modelBuilder.Entity<Eventi>(entity =>
        {
            entity.Property(e => e.Località).IsRequired();
            entity.Property(e => e.Nome).IsRequired();
        });

        modelBuilder.Entity<Speakers>(entity =>
        {
            entity.HasIndex(e => e.EventoId, "IX_Speakers_EventoId");

            entity.Property(e => e.Nome).IsRequired();

            entity.HasOne(d => d.Evento).WithMany(p => p.Speakers).HasForeignKey(d => d.EventoId);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}